name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      SERVER_HOST: ${{secrets.SERVER_HOST}}
      SERVER_USER: ${{secrets.SERVER_USER}}
      PORT: ${{secrets.PORT}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
    steps:
      - name: Deploy to server
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrickHostKeyChecking=no $SERVER_USER@$SERVER_HOST <<EOF
          cd home/ubuntu/app
          echo "POST=${PORT}" > .env
          echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
          echo "POSTGRES_DB=${POSTGRES_DB}" >> .env
          sudo docker compose down
          sudo docker compose up --build -d
          EOF
